services:
  - name: myapp
    type: web
    env: python
    plan: free
    buildCommand: ""
    startCommand: >
      celery -A myapp worker --loglevel=info & 
      celery -A myapp beat --loglevel=info & 
      gunicorn -b 0.0.0.0:$PORT myapp:app

    envVars:
      - key: SECRET_KEY
        value: rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx
      - key: DATABASE_URL
        value: postgresql://samson:rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx@dpg-cp356lvsc6pc73fjcimg-a/samson_vjsf
      - key: REDIS_URL
        value: redis://red-cpo2mtdds78s73b95tpg:6379/0
      - key: CELERY_BROKER_URL
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE
      - key: CELERY_RESULT_BACKEND
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE

    build:
      - pip install -r requirements.txt

jobs:
  - name: celery-worker
    type: worker
    env: python
    plan: free
    buildCommand: ""
    startCommand: celery -A myapp worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        value: rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx
      - key: DATABASE_URL
        value: postgresql://samson:rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx@dpg-cp356lvsc6pc73fjcimg-a/samson_vjsf
      - key: REDIS_URL
        value: redis://red-cpo2mtdds78s73b95tpg:6379/0
      - key: CELERY_BROKER_URL
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE
      - key: CELERY_RESULT_BACKEND
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE

  - name: celery-beat
    type: worker
    env: python
    plan: free
    buildCommand: ""
    startCommand: celery -A myapp beat --loglevel=info
    envVars:
      - key: SECRET_KEY
        value: rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx
      - key: DATABASE_URL
        value: postgresql://samson:rxo9pRal2PjcuzRcFIPfGgqHrlLnAwmx@dpg-cp356lvsc6pc73fjcimg-a/samson_vjsf
      - key: REDIS_URL
        value: redis://red-cpo2mtdds78s73b95tpg:6379/0
      - key: CELERY_BROKER_URL
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE
      - key: CELERY_RESULT_BACKEND
        value: rediss://red-cpo2mtdds78s73b95tpg:6379/0?ssl_cert_reqs=CERT_NONE
