"""Add closing_time to Location model

Revision ID: 68380229fcf5
Revises: 0efcf529f836
Create Date: 2024-06-15 22:17:11.818302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68380229fcf5'
down_revision = '0efcf529f836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_time', sa.Time(), nullable=True))
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'2024-12-31 00:00:00'::timestamp without time zone"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'2024-12-31 00:00:00'::timestamp without time zone"))
        batch_op.drop_column('closing_time')

    # ### end Alembic commands ###
